<a href="https://colab.research.google.com/github/sonjoy1s/NLP/blob/main/IMDB_Dataset_of_50K_Movie_ReviewsNLPModule9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("/content/IMDB Dataset.csv.zip")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [7]:
df.isna().sum()

review       0
sentiment    0
dtype: int64

In [8]:
df.columns

Index(['review', 'sentiment'], dtype='object')

In [11]:
df['review'][2].lower()

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.<br /><br />this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

In [13]:
df['review'] = df['review'].str.lower()  # review ke lower case convert

In [14]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [21]:
#htlm Tag removed
import re
def removed_html_tags(text):
  pattern = re.compile(r"<.*?>")

  return pattern.sub(r'', text)

In [27]:
#removed_html_tags(df['review'][3])

In [28]:
df['review'] = df['review'].apply(removed_html_tags)

In [29]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [30]:
#Removed Url
text1= '''
Yesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on https://phitron.io and also watched tutorials at https://www.youtube.com/watch?v=dQw4w9WgXcQ.

For research papers, I visited https://arxiv.org/abs/1706.03762 and read documentation from https://pytorch.org/docs/stable/index.html. One of my friends also shared a blog post available at www.medium.com/@ai_engineer/transformers-explained.

If you'd like to practice coding problems, check out https://leetcode.com/problemset/ or https://www.kaggle.com/datasets. These websites are very helpful for aspiring AI engineers.

'''

In [31]:
text1

"\nYesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on https://phitron.io and also watched tutorials at https://www.youtube.com/watch?v=dQw4w9WgXcQ.\n\nFor research papers, I visited https://arxiv.org/abs/1706.03762 and read documentation from https://pytorch.org/docs/stable/index.html. One of my friends also shared a blog post available at www.medium.com/@ai_engineer/transformers-explained.\n\nIf you'd like to practice coding problems, check out https://leetcode.com/problemset/ or https://www.kaggle.com/datasets. These websites are very helpful for aspiring AI engineers.\n\n"

In [33]:
def removed_url(text):
  pattern = re.compile(r"https?://|S+|www\.\S+")
  return pattern.sub(r'', text)

In [34]:
text1 = removed_url(text1)
text1

"\nYesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on phitron.io and also watched tutorials at \n\nFor research papers, I visited arxiv.org/abs/1706.03762 and read documentation from pytorch.org/docs/stable/index.html. One of my friends also shared a blog post available at \n\nIf you'd like to practice coding problems, check out leetcode.com/problemset/ or  These websites are very helpful for aspiring AI engineers.\n\n"